### ISSUE TITLE
secretome_qusetions

### ISSUE THREAD

**Issue by williamwuyulu** [Bastiaanspanjaard/Heart_regeneration#1]
Hi,

amazing work done here!

I have a question, I would like to rerun the "Translate_secretome.R" by using our own dataset. For testing purposes, I want to start with a human dataset. So I noticed a line of code in the Translate_secretome.R
`human_secretome <- fread("~/Documents/Projects/heart_Bo/Data/Human_secretome.tsv")`
But I don't know how the Human_secretome.tsv file is obtained? Did the author make it himself or did he download it? It would be great if you could share the link or the file that you!

Thanks so much for the help!

Best,

William

@BSpanjaard 
@Bastiaanspanjaard

**Comment by Bastiaanspanjaard** [comment]
Hey William,

Thanks for the kind words. We obtained the human secretome from the Vertebrate Secretome Database (http://genomics.cicbiogune.es/VerSeDa/index.php). I have added the datafile we used to the ./Data/-folder of the repository.

Cheers,
Bastiaan

**Comment by williamwuyulu** [comment]
Hi Bastiaan，

Great!

Thank you much for your help.

Best,

William
