### ISSUE TITLE
Three questions about   heartregen_clustering.R

### ISSUE THREAD

**Issue by zebrakang** [Bastiaanspanjaard/Heart_regeneration#2]
Dear Bastiaan, 

Thank you so much for your sharing your fantastic work!
I followed the scripts of heartregen_clustering.R, but encountered some problems.
Would you please help me resolve these?

I have three questions.

1. Hr2 dataset
Hr2a and Hr2b dataset -> When I unzipped, GEO deposited file (GSE150932_RAW.tar and GSE158919_RAW.tar), there are Hr2 and Hr2_morecells, not Hr2a and Hr2b.
I expect that Hr2 would be Hr2a and Hr2_morecells would be Hr2b.

2. Error 
When I run the script "all.hearts <- subset(all.hearts,cells = rownames(all.hearts@meta.data)[!is.na(all.hearts@meta.data$celltypes)],)" error occurs. 
Error: Cannot add more or fewer cell meta.data information without values being named with cell names
I am wondering whether you could help fix it.
I copied and pasted a csv file to notepad and saved it.
The csv file has 202255, but cell number of all.hearts seurat data has 283818.

3. cluster number
The total cluster number is 108, not 102...
It may be caused by the failure of filtering erythrocytes and dead cells (see above).

I again sincerely appreciate you for sharing your wonderful work!

Best,
Junsu Kang

**Comment by Bastiaanspanjaard** [comment]
Dear Junsu,

Thanks for the kind words!

You're correct in your first point, Hr2 and Hr2_morecells are indeed Hr2a and Hr2b.

For your second and third question: are you looking to rerun the clustering script or would you also be helped by having the full single-cell object? Because if it's the second, there might be a better long-term solution. Please let me know!

Cheers,
Bastiaan

**Comment by zebrakang** [comment]
Hi Bastiaan,

Thank you for your quick response.
I would like to rerun the clustering script.
You already did a great job! The cluster number is truly impressive, so I want to follow your way. 
The goal is to check which clusters belong genes that I am working.
What I found is that filtering with percent.mito < 25 and nFeature_RNA<4100 generates more cells. 
For example, the cell numbers of H5 and H6 are 2470 and 4534, not 2095 and 3444.
I think that there would be another filtering...
I reran the following script you uploaded... 

for (i in batches) {
  gather.data[[i]] <- Read10X_h5(filename = paste0(i,"_filtered_matrix.h5") )
  RFP.index <- grep(pattern = "^RFP", x = rownames(gather.data[[i]]), value = FALSE) # Select row indices and not ERCC names 
  gather.data[[i]] <- gather.data[[i]][-RFP.index, ]
  gather.data[[i]] <- CreateSeuratObject(counts = gather.data[[i]],
                                         min.cells = 3, min.features = 150,
                                         project = i)
  mito.genes.use <- setdiff(mito.genes,setdiff(mito.genes,rownames(gather.data[[i]][["RNA"]])))
  gather.data[[i]][["percent.mito"]] <- PercentageFeatureSet(object = gather.data[[i]], features = mito.genes.use)
  gather.data[[i]] <- subset(x = gather.data[[i]], subset = percent.mito < 25 & nFeature_RNA < 4100)
  data.stats[i] <- length(colnames(x = gather.data[[i]]))
}

# stats
print(data.stats)

Thank you for your help.

Best,
Junsu Kang

**Comment by Bastiaanspanjaard** [comment]
Hey Junsu,

First of all, you'll need slightly different code than currently in the repository to add the cell.ids as metadata:
```
cell.id.table <- read.csv("cell.id.table.csv", row.names = "X")
row.names(cell.id.table) <- paste0(row.names(cell.id.table), "-1")
all.hearts <- AddMetaData(all.hearts,cell.id.table)
```
Then performing the subsetting yields a total of 202255 cells. I will push a fix for this soon.

Second, could you please tell me which Seurat version you are running? Different Seurat versions have slightly different clustering results and ours were generated using Seurat 3.0.0. If you are running a different version, your results will not substantially change but you will get small deviations such as a different initial cluster number or a different UMAP layout.

**Comment by zebrakang** [comment]
Hi Bastiaan,

Thank you for your script.
Your script is likely working on adding metadata, but still cell number after filtration is not the same.
The total cell number I got is 283818 and the cluster number is 108.

I am using Seurat 4.1.0.

I will try to use Seurat 3.0.0. Or, using supplementary table 2, need to analyze cell types. 
I appreciate your sharing of marker genes!
As I am off for a week, I will do these after that.

Thank you again for your kindness and quick response.

Best,
Junsu Kang

**Comment by Bastiaanspanjaard** [comment]
Hi Junsu,

I have pushed a fix that should allow you to keep only the cells in cell.id.table.csv so you should end up with 202255 cells. Please have a look if it works for you.

After that, for Seurat version different than 3.0.0, you may not obtain exactly the same clusters as we did. However, using the table Data/final_celltypes.tsv, you can find the actual cell type of every cell (a couple are slightly adjusted in the script Heart_regen_Seurat_analysis.R) so you could use that to easily determine the identities of the clusters you have.

I will leave this issue open for the next week so you can comment once you are back.

Cheers,
Bastiaan

**Comment by Bastiaanspanjaard** [comment]
Closing as resolved.
