### ISSUE TITLE
Some questions about Sequencing library

### ISSUE THREAD

**Issue by baoyulinn** [Bastiaanspanjaard/Heart_regeneration#3]
First, I haved downloaded the SRR files from GEO and use parallel-fastq-dump to transfer these files into fastq files. However, the size of the converted fastq file is not the same as the one you uploaded before. 
<img width="738" alt="image" src="https://user-images.githubusercontent.com/111479371/211235700-8a1a63bc-b515-4b90-a32e-ac6c09a69047.png">
<img width="269" alt="image" src="https://user-images.githubusercontent.com/111479371/211235734-1ed1a896-3693-47e8-8cec-59786059d656.png">

Second, The file after processing with cellranger, where "average nUMI per cell", "average nGene per cell", and "number of cells", is different from what you summarized in the Supplementary Data File 1.
<img width="742" alt="image" src="https://user-images.githubusercontent.com/111479371/211236059-c63b9a75-87f0-4d23-8be5-aabdeeaed3c0.png">
<img width="743" alt="image" src="https://user-images.githubusercontent.com/111479371/211236071-3609595f-6521-446a-b1b7-a250c8c3730c.png">

`parallel-fastq-dump -t 23  -O Hr2/ --split-files --gzip SRR12774363`
`cellranger count --id=10x_H6 --transcriptome=/home/shpc_101231/zebrafish_heart_sc/Rawdata/reference/Danio.rerio_genome --fastqs=/home/shpc_101231/zebrafish_heart_sc/Rawdata/H6 --sample=SRR12774358 --nosecondary
`

Maybe I have a problem somewhere and I hope you can answer it, thank you very much.

**Comment by Bastiaanspanjaard** [comment]
Hello baoyulinn,

Thanks for raising this.

Your first issue sounds very much like parallel-fastq-dump adds a little bit of data to the fastq files. I would assume this won't affect alignment and downstream analysis. If you'd like to be sure, we can check this: could you please add the first four lines of a matched pair of R1 and R2 fastq-files (e.g. from SRR12774363/Hr2_7dpi[...])? Then I can compare this to what they look like on my end to see what's different.

The summary in Supplemental Data File 1 is after a further filtering quality control + filtering step. This can be found in heartregen_clustering.R. Please also note that different versions of cellranger may impose different cell selection criteria and that your results may therefore be different from ours. You could circumvent this by supplying the cellular barcodes we extract as a whitelist to cellranger.

**Comment by Bastiaanspanjaard** [comment]
Closing as resolved.
